// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// normalize_phi
Rcpp::NumericMatrix normalize_phi(Rcpp::NumericMatrix phi, Rcpp::NumericVector work_grid);
RcppExport SEXP _hdfda_normalize_phi(SEXP phiSEXP, SEXP work_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type work_grid(work_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_phi(phi, work_grid));
    return rcpp_result_gen;
END_RCPP
}
// get_fpc_scores
Rcpp::NumericMatrix get_fpc_scores(Rcpp::NumericMatrix X, Rcpp::NumericMatrix phi, Rcpp::NumericVector work_grid);
RcppExport SEXP _hdfda_get_fpc_scores(SEXP XSEXP, SEXP phiSEXP, SEXP work_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type work_grid(work_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(get_fpc_scores(X, phi, work_grid));
    return rcpp_result_gen;
END_RCPP
}
// trapzRcpp
double trapzRcpp(const Rcpp::NumericVector X, const Rcpp::NumericVector Y);
RcppExport SEXP _hdfda_trapzRcpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(trapzRcpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdfda_normalize_phi", (DL_FUNC) &_hdfda_normalize_phi, 2},
    {"_hdfda_get_fpc_scores", (DL_FUNC) &_hdfda_get_fpc_scores, 3},
    {"_hdfda_trapzRcpp", (DL_FUNC) &_hdfda_trapzRcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdfda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
