# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize_phi <- function(phi, work_grid) {
    .Call(`_hdfda_normalize_phi`, phi, work_grid)
}

get_fpc_scores <- function(X, phi, work_grid) {
    .Call(`_hdfda_get_fpc_scores`, X, phi, work_grid)
}

group_scad_flr_cpp <- function(Y, Theta, p, s, lambda, a = 3.7, max_iter = 100L, tol = 1e-6) {
    .Call(`_hdfda_group_scad_flr_cpp`, Y, Theta, p, s, lambda, a, max_iter, tol)
}

solve_mm_bcd <- function(X, y, Lambda_diag, beta_init, p, s, lambda, a = 3.7, max_iter_outer = 1000L, sweeps_inner = 2L, tol_outer = 1e-5, epsilon = 1e-6) {
    .Call(`_hdfda_solve_mm_bcd`, X, y, Lambda_diag, beta_init, p, s, lambda, a, max_iter_outer, sweeps_inner, tol_outer, epsilon)
}

#' Trapezoid Rule Numerical Integration
#'
#' Trapezoid Rule Numerical Integration using Rcpp
#' @param X Sorted vector of X values
#' @param Y Vector of Y values.
#' @export
trapzRcpp <- function(X, Y) {
    .Call(`_hdfda_trapzRcpp`, X, Y)
}

